# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0004_auto_20160812_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfaceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=30)),
                ('method', models.CharField(max_length=7)),
                ('header', models.TextField()),
                ('request_body', models.TextField()),
                ('response_code', models.CharField(max_length=3)),
                ('response_body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='BlogsPost',
        ),
    ]
