# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autotest', '0006_blogspost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogsPost',
        ),
        migrations.DeleteModel(
            name='InterfaceList',
        ),
    ]
